controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_catch_all_route:
    path: /{catchAll}
    controller: App\Controller\MainController::homePage
    requirements:
        catchAll: ".+"
